############# English navigation ##############
# main menu    
[[main]]
name = "Service"
URL = "service"
weight = 2

[[main]]
name = "Pricing"
URL = "pricing"
weight = 3

[[main]]
name = "Contact"
URL = "contact"
weight = 4

[[main]]
name = "About"
URL = "about"
weight = 5

[[main]]
name = "Pages"
weight = 6
hasChildren = true

  [[main]]
  parent = "Pages"
  name = "Career"
  URL = "career"
  
  [[main]]
  parent = "Pages"
  name = "Team"
  URL = "team"

  [[main]]
  parent = "Pages"
  name = "FAQ"
  URL = "faq"
  
  [[main]]
  parent = "Pages"
  name = "Changelog"
  URL = "changelog"

#Footer menu
[[footer]]
name = "Company History"
URL = "about"

[[footer]]
name = "About us"
URL = "about"

[[footer]]
name = "Contact us"
URL = "contact"

[[footer]]
name = "Privacy Policy"
URL = "#"